/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MultiSigInterface extends Interface {
    getFunction(nameOrSignature: "isSigned" | "owners" | "requiredSignatures" | "signTransaction" | "submitTransaction" | "transactions"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TransactionExecuted" | "TransactionProposed"): EventFragment;

    encodeFunctionData(functionFragment: 'isSigned', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'owners', values?: undefined): string;
encodeFunctionData(functionFragment: 'requiredSignatures', values?: undefined): string;
encodeFunctionData(functionFragment: 'signTransaction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitTransaction', values: [string, AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transactions', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'isSigned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requiredSignatures', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transactions', data: BytesLike): Result;
  }

  
    export namespace TransactionExecutedEvent {
      export type InputTuple = [to: AddressLike, data: BytesLike];
      export type OutputTuple = [to: string, data: string];
      export interface OutputObject {to: string, data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransactionProposedEvent {
      export type InputTuple = [transactionId: BigNumberish, proposer: AddressLike];
      export type OutputTuple = [transactionId: bigint, proposer: string];
      export interface OutputObject {transactionId: bigint, proposer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MultiSig extends BaseContract {
    
    connect(runner?: ContractRunner | null): MultiSig;
    waitForDeployment(): Promise<this>;

    interface: MultiSigInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    isSigned: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owners: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    requiredSignatures: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    signTransaction: TypedContractMethod<
      [transactionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitTransaction: TypedContractMethod<
      [functionSignature: string, tokenContract: AddressLike, receiver: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transactions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, boolean, string, bigint] & {to: string, executed: boolean, data: string, signatureCount: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'isSigned'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owners'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'requiredSignatures'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'signTransaction'): TypedContractMethod<
      [transactionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitTransaction'): TypedContractMethod<
      [functionSignature: string, tokenContract: AddressLike, receiver: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transactions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, boolean, string, bigint] & {to: string, executed: boolean, data: string, signatureCount: bigint }],
      'view'
    >;

    getEvent(key: 'TransactionExecuted'): TypedContractEvent<TransactionExecutedEvent.InputTuple, TransactionExecutedEvent.OutputTuple, TransactionExecutedEvent.OutputObject>;
getEvent(key: 'TransactionProposed'): TypedContractEvent<TransactionProposedEvent.InputTuple, TransactionProposedEvent.OutputTuple, TransactionProposedEvent.OutputObject>;

    filters: {
      
      'TransactionExecuted(address,bytes)': TypedContractEvent<TransactionExecutedEvent.InputTuple, TransactionExecutedEvent.OutputTuple, TransactionExecutedEvent.OutputObject>;
      TransactionExecuted: TypedContractEvent<TransactionExecutedEvent.InputTuple, TransactionExecutedEvent.OutputTuple, TransactionExecutedEvent.OutputObject>;
    

      'TransactionProposed(uint256,address)': TypedContractEvent<TransactionProposedEvent.InputTuple, TransactionProposedEvent.OutputTuple, TransactionProposedEvent.OutputObject>;
      TransactionProposed: TypedContractEvent<TransactionProposedEvent.InputTuple, TransactionProposedEvent.OutputTuple, TransactionProposedEvent.OutputObject>;
    
    };
  }