/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Community42__factory } from './Community42__factory.js';
export { MultiSig__factory } from './MultiSig__factory.js';